trigger:
- master

stages:
- stage: Build
  jobs:
  - job:
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        echo 'build my app'
      displayName: 'build'

- stage: Test
  jobs:
  - job:
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        echo 'test my app'
      displayName: 'test'
  dependsOn: Build

- stage: Staging
  jobs:
  - job:
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        echo 'deploy my app'
      displayName: 'deploy'
  dependsOn: Test

- stage: Production
  jobs:
  - job:
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
    - script: |
        echo 'deploy my app'
      displayName: 'deploy'
  dependsOn: Staging